In [42]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

df=pd.read_csv("./datasets./bank-additional-full.csv",sep=';')
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [43]:
df_pre=df['previous']
df_pre


###이미 수치형 데이터로 존재

0        0
1        0
2        0
3        0
4        0
        ..
41183    0
41184    0
41185    0
41186    0
41187    1
Name: previous, Length: 41188, dtype: int64

In [44]:
pout=df['poutcome']
pout


0        nonexistent
1        nonexistent
2        nonexistent
3        nonexistent
4        nonexistent
            ...     
41183    nonexistent
41184    nonexistent
41185    nonexistent
41186    nonexistent
41187        failure
Name: poutcome, Length: 41188, dtype: object

In [45]:
pout= pout.apply(lambda x: x.replace('failure','0'))
pout = pout.apply(lambda x: x.replace('success','1'))
pout = pout.apply(lambda x: x.replace('nonexistent','2'))


In [46]:
encorder=LabelEncoder()
encorder.fit(pout)
labels_p=encorder.transform(pout)
labels_p
# pd.DataFrame(labels,index=index,columns="poutcome")

array([2, 2, 2, ..., 2, 2, 0])

In [47]:
labels_p=labels_p.reshape(-1,1)
oh_encorder=OneHotEncoder()
oh_encorder.fit(labels_p)
oh_labels_p=oh_encorder.transform(labels_p)
oh_labels_p.toarray()


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [48]:
y=df['y']
y

0         no
1         no
2         no
3         no
4         no
        ... 
41183    yes
41184     no
41185     no
41186    yes
41187     no
Name: y, Length: 41188, dtype: object

In [49]:
encorder=LabelEncoder()
encorder.fit(y)
labels_y=encorder.transform(y)
labels_y

array([0, 0, 0, ..., 0, 1, 0])

In [50]:
df_test = df
df_test['y'] = labels_y
df_test['poutcome']=labels_p
df_test.drop(['contact','month','day_of_week','campaign','emp.var.rate','cons.price.idx','euribor3m','nr.employed','cons.conf.idx'],axis=1,inplace=True)   ### []가 하나만 있어야된다 이말이야
df_test


age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

       duration  pdays  previous  poutcome  cons.conf.idx  y  
0           261    999         0         2          -36.4  0  
1           149    999         0         2          -36.4  0  
2           226    999         0         2          -36.4  0  
3           151    999         0         2          -36.4  0  
4           307    999         0         2          -36.4  0  
...         ...    ...       ...       ...            ... ..  
41183       334    999         0         2          -50.8  1  
41184       383    999         0         2          -50.8  0  
41185       189    999         0         2          -50.8  0  
41186       442    999         0         2          -50.8  1  
41187       239    999         1         0          -50.8  0  

[41188 rows x 13 columns]

In [51]:
pout.unique()

array(['2', '0', '1'], dtype=object)

In [52]:
# labels_y=labels_y.reshape(-1,1)
# oh_encorder=OneHotEncoder()
# oh_encorder.fit(labels_y)
# oh_labels_y=oh_encorder.transform(labels_y)
# oh_labels_y.toarray()